/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/yMsl5zXKSml
 */
import { Link, useNavigate } from "@tanstack/react-router";
import { SVGProps } from "react";
import { JSX } from "react/jsx-runtime";

export function globalError404() {
  const navigate = useNavigate({ from: "/home" });

  return (
    <div className="min-w-full flex flex-col items-center justify-center min-h-full bg-transparent absolute  top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
      <div className="text-[192px] leading-none font-bold text-primary dark:text-white">
        <span>4</span>
        <DonutIcon className="inline-block w-[192px] h-[192px] text-primary" />
        <span>4</span>
      </div>
      <h1 className="mt-8 text-4xl font-semibold text-gray-800 dark:text-white">
        Oopsie! Something's missing...
      </h1>
      <p className="mt-4 text-lg text-gray-600 dark:text-gray-300">
        It seems like we donut find what you searched. The page you were looking
        for doesn't exist, isn't available or was loading incorrectly.
      </p>
      <Link
        to="/home/welcome"
        className="mt-8 px-6 py-3 text-lg font-med text-white font-bold bg-primary rounded"
      >
        Back To Home
      </Link>
    </div>
  );
}

function DonutIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.5 10a2.5 2.5 0 0 1-2.4-3H18a2.95 2.95 0 0 1-2.6-4.4 10 10 0 1 0 6.3 7.1c-.3.2-.8.3-1.2.3" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}
